### ISSUE TITLE
Gluster ops complying AbstractOps

### ISSUE THREAD

**Issue by aujjwal-redhat** [srijan-sivakumar/redant#221]
Gluster Ops still does not extend the abstract ops functionalities.

**Comment by srijan-sivakumar** [comment]
The decision taken is to take a middle road here. We cannot be too stringent and worship the frameworks and the software methodology but at the same time we cannot throw everything out of the window just because we want to push changes fast. We will be using abstract ops ( seriously..somebody rename it, it is too misleading ) but at the same time, only at places wherein we don't have to compromise on the functionality in the ops function. Hence converting this into a discussion.
