### ISSUE TITLE
Custom setup variable instantiation to be left to framework

### ISSUE THREAD

**Issue by srijan-sivakumar** [srijan-sivakumar/redant#742]
It is a little annoying from the user perspective to handle and modify a variable and not having the freedom to just focus on the test case logic.

There is support of a custom setup in redant but it is a little convoluted. The user would have to override the parent class's setup but along with that, they also need to set a variable inside the setup function to tell the framework that they have invoked the custom setup and don't want the framework's help for setting up an env.

How it is to be done ?

That is the focus of this issue.

**Comment by srijan-sivakumar** [comment]
Setup can also be useful for telling the framework the pre-conditions to be checked before starting a test case rather than having the preconditions inside the test case.

**Comment by nik-redhat** [comment]
Doing the setup part on its own and not using the framework's parent_class is part of the test case logic, so I don't find any issue in that :thinking: 
Moreover, what actually should be changed is the order in which the cluster is formed beforehand. That is the functions `create_cluster` and `delete_cluster` should be called inside the custom `setup_test` function because in many cases we don't want to use the complete cluster for the test, and in such cases the there is an overhead to `delete` the _just created_ cluster.

**Comment by nik-redhat** [comment]
Setup can be checked but doesn't make much sense because the requirements can vary a lot for different scenarios, and sometimes it is done intentionally to use a smaller setup for some test.
